name: 企鹅读书

on:
  workflow_dispatch:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
  watch:
    types: [started]
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: '运行【企鹅读书】' 
        run: python3 qqread.py 
        env:
            QQREADHEADERS: ${{ secrets.QQREADHEADERS }}
            QQREADBODYS: ${{ secrets.QQREADBODYS }}
            QQREADTIMEURL: ${{ secrets.QQREADTIMEURL }}
            NOTIFYTYPE: ${{ secrets.NOTIFYTYPE }}
            NOTIFYCFG: ${{ secrets.NOTIFYCFG }}
            DRAWAMOUNT: ${{ secrets.DRAWAMOUNT }}
            SCKEY: ${{ secrets.SCKEY }}
         
